from yalul.interpreters.interpreter_errors import InterpreterErrors
from yalul.parsers.ast.nodes.statements.expression import Expression
from yalul.interpreters.expression import ExpressionInterpreter

INTERPRETERS = {}


class Interpreter:
    """
    Yalul's interpreter, all your code is interpreted here
    """

    def __init__(self, ast):
        """
        Construct a new ExpressionParser object.

        :ast: An AST object generated by Parser
        :return: Interpreter object
        """
        self.ast = ast

    def run(self):
        """
        Interpret all statements from self.ast

        :return: None
        """

        for statement in self.ast.statements:
            error = InterpreterErrors()

            response = self.interpret(statement, error)

            if error.errors:
                for interpreter_error in error.errors:
                    print(interpreter_error)

                next
            else:
                print(response)

    def interpret(self, statement, error):
        """
        Interpret any given statement
        """

        if INTERPRETERS.get(type(statement)):
            return None
        elif isinstance(statement, Expression):
            return ExpressionInterpreter.execute(statement, error)
        else:
            return None
