from yalul.utils.lex.graphviz_printer import GraphvizPrinter


class LexTokensPrinter:
    """
    Lex Tokens Printer will print lex tokens generated by lex in a pretty way based on supported outputs types
    """

    def __init__(self, tokens, format='pdf'):
        """
        Construct a new LexTokensPrinter object.

        :param tokens: An array of lex tokens
        :output: Output format of the print
        :return: LexTokensPrinter object
        """
        self.tokens = tokens
        self.format = format

    def print(self):
        """
        Print lex tokens in the given file output
        """
        if self.format == 'pdf':
            GraphvizPrinter(self.tokens).generate_pdf()
